### ISSUE TITLE
Preferred way of loading RT-X files with a local buffer

### ISSUE THREAD

**Issue by utn-blei** [BerkeleyAutomation/fog_x#14]
Hello, 

thanks for the good work!

What is the preferred way of loading the RT-X dataset with a local buffer?
When using the _load_rtx_episodes_ function, the dataset is freshly downloaded from the google gs server, whenever we run the code. This slows down training significantly. 

I could overwrite the _dataset2path_ function, however this is probably not the intended way of using the framework :)
We're happy to contribute if this involves implementing a new feature.

Greetings,

Yannik

**Comment by KeplerC** [comment]
Hi Yannik, 

Thanks for your interest! I'm wondering #15 would solve your issue. 

I have already merged with main branch, so you should be able to clone and install from source. I may plan for a pip package release by the end of the week.

**Comment by utn-blei** [comment]
This helps, thanks for the quick reply! :)

**Comment by utn-blei** [comment]
Looks like we introduced an error here ... when running

`    dataset.load_rtx_episodes(
        name="berkeley_autolab_ur5", additional_metadata={"collector": "User 2"}
    )`

python yields

`TypeError: Dataset._build_rtx_episodes_from_tfds_builder() got an unexpected keyword argument 'split'`

The solution should be as easy as adding `split: str = "all",` in line 423, dataset.py

Could you verify?

**Comment by utn-blei** [comment]
PS: I cannot reopen the issue - seems like it is disabled for this repo

**Comment by NotAFood** [comment]
Hi @utn-blei, I've made you an outside collaborator on this project so that you can reopen your own issues with it in the future. Unfortunately this has to be done on a person-by-person and repo-by-repo basis but should solve your problem for now.

~ AUTOLAB Systems Administration

**Comment by utn-blei** [comment]
Hi @NotAFood, thanks a lot!
[@juelg](https://github.com/juelg) and I would be happy to contribute in the future.
Is there any specific way you handle the discussion of new features?
Greetings from UTN in Germany :-)

**Comment by NotAFood** [comment]
@utn-blei , I've activated the discussions tab for the repository if you would like to discuss new features. Any post on there should notify the other repository members.
